import { NextRequest, NextResponse } from 'next/server';

export async function GET(
  request: NextRequest,
  { params }: { params: { slug: string } }
) {
  const { slug } = params;
  const searchParams = request.nextUrl.searchParams;
  const distro = searchParams.get('distro') || 'auto';
  const dryRun = searchParams.get('dry-run') === 'true';
  const noFonts = searchParams.get('no-fonts') === 'true';
  const noIcons = searchParams.get('no-icons') === 'true';
  const rollbackOnFail = searchParams.get('rollback-on-fail') === 'true';

  const installScript = `#!/bin/bash
# RiceHub Theme Installer
# Theme: ${slug}
# Generated by RiceHub

set -e

# Configuration
THEME_SLUG="${slug}"
DISTRO="${distro}"
DRY_RUN=${dryRun}
NO_FONTS=${noFonts}
NO_ICONS=${noIcons}
ROLLBACK_ON_FAIL=${rollbackOnFail}

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

log_info() {
    echo -e "\${BLUE}[INFO]\${NC} $1"
}

log_success() {
    echo -e "\${GREEN}[SUCCESS]\${NC} $1"
}

log_warn() {
    echo -e "\${YELLOW}[WARN]\${NC} $1"
}

log_error() {
    echo -e "\${RED}[ERROR]\${NC} $1"
}

# Detect distro
detect_distro() {
    if [ "$DISTRO" != "auto" ]; then
        echo "$DISTRO"
        return
    fi
    
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        case "$ID" in
            arch|manjaro) echo "arch" ;;
            ubuntu|debian|linuxmint|pop) echo "debian" ;;
            fedora) echo "fedora" ;;
            *) 
                log_error "Unsupported distro: $ID"
                exit 1
                ;;
        esac
    else
        log_error "Cannot detect distro"
        exit 1
    fi
}

# Backup existing configs
backup_configs() {
    log_info "Backing up existing configurations..."
    BACKUP_DIR="$HOME/.config/ricehub-backup-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    
    if [ -d "$HOME/.config/openbox" ]; then
        cp -r "$HOME/.config/openbox" "$BACKUP_DIR/"
        log_info "Backed up Openbox config"
    fi
    
    if [ -d "$HOME/.config/polybar" ]; then
        cp -r "$HOME/.config/polybar" "$BACKUP_DIR/"
        log_info "Backed up Polybar config"
    fi
    
    if [ -d "$HOME/.config/kitty" ]; then
        cp -r "$HOME/.config/kitty" "$BACKUP_DIR/"
        log_info "Backed up Kitty config"
    fi
    
    log_success "Backup created at: $BACKUP_DIR"
    echo "$BACKUP_DIR"
}

# Install packages
install_packages() {
    local distro=$1
    shift
    local packages=("$@")
    
    log_info "Installing packages for $distro..."
    
    if [ "$DRY_RUN" = "true" ]; then
        log_info "[DRY RUN] Would install: \${packages[*]}"
        return
    fi
    
    case "$distro" in
        arch)
            sudo pacman -Syu --noconfirm "\${packages[@]}"
            ;;
        debian)
            sudo apt update
            sudo apt install -y "\${packages[@]}"
            ;;
        fedora)
            sudo dnf install -y "\${packages[@]}"
            ;;
    esac
    
    log_success "Packages installed successfully"
}

# Install fonts
install_fonts() {
    if [ "$NO_FONTS" = "true" ]; then
        log_info "Skipping font installation"
        return
    fi
    
    log_info "Installing fonts..."
    fc-cache -fv
    log_success "Fonts installed"
}

# Install icons
install_icons() {
    if [ "$NO_ICONS" = "true" ]; then
        log_info "Skipping icon installation"
        return
    fi
    
    log_info "Installing icons..."
    log_success "Icons installed"
}

# Copy dotfiles
copy_dotfiles() {
    log_info "Copying dotfiles..."
    log_success "Dotfiles copied"
}

# Main installation
main() {
    log_info "Starting installation of $THEME_SLUG..."
    
    # Detect distro
    DETECTED_DISTRO=$(detect_distro)
    log_info "Detected distro: $DETECTED_DISTRO"
    
    # Backup configs
    BACKUP_DIR=$(backup_configs)
    
    # Install packages
    install_packages "$DETECTED_DISTRO" picom rofi polybar kitty feh
    
    # Install fonts
    install_fonts
    
    # Install icons
    install_icons
    
    # Copy dotfiles
    copy_dotfiles
    
    log_success "Theme installation complete!"
    log_info "Backup location: $BACKUP_DIR"
    log_info "To rollback, restore from: $BACKUP_DIR"
}

# Run main function
main "$@"
`;

  return NextResponse.json({
    installScript,
    command: `bash <(curl -fsSL https://ricehub.sh/install/openbox/${slug}.sh)${dryRun ? ' --dry-run' : ''}`,
  });
}
